# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv003Beta < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.3-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.3-beta/dive-cli_v0.0.3-beta_darwin_arm64.tar.gz"
      sha256 "71ffcd9f82ca56d503e6f3b5b2a730a9632f542dabe47927d3548f36f0955484"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.3-beta/dive-cli_v0.0.3-beta_darwin_amd64.tar.gz"
      sha256 "9e59626542dccbf1dc1c1377879c609ef55db8ce4ea354b1cc39923abbf015bb"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.3-beta/dive-cli_v0.0.3-beta_linux_arm64.tar.gz"
      sha256 "4689ddbf21e11b423d84019d1971769b461f59cb3120720901d0f9a0f2b0bf42"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.3-beta/dive-cli_v0.0.3-beta_linux_amd64.tar.gz"
      sha256 "c09d54e8e7261324d4419ee4cc7e137e09b3c9e93b0062a378b071a1ffe9fc81"

      def install
        bin.install "dive"
      end
    end
  end
end
