# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATV011 < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.1.1"
  license "Apache 2.0"

  depends_on "kurtosis-cli@0.87.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.1/dive-cli_v0.1.1_darwin_arm64.tar.gz"
      sha256 "545430df6d2f6c7a89f86a9eeab24b026ec39f89b2828593ff1e80e73387d839"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.1/dive-cli_v0.1.1_darwin_amd64.tar.gz"
      sha256 "1eba1f94568fe28828ce40c1f718bc10d8e63cd26623fb0022d06c0955483e2c"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.1/dive-cli_v0.1.1_linux_arm64.tar.gz"
      sha256 "1a28b77b580ba2a7fd32b987fa5d3e3c8ce69fba601b20ed244b23af55d0257c"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.1/dive-cli_v0.1.1_linux_amd64.tar.gz"
      sha256 "865172395e9e0d0712f8f6ef9a91d76dcd6069059deb08d069d65d17f80dbc22"

      def install
        bin.install "dive"
      end
    end
  end
end
