# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv005Beta < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.5-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.5-beta/dive-cli_v0.0.5-beta_darwin_amd64.tar.gz"
      sha256 "3ac813b66c987c289995cf8b414e025f5b44b4537befc6f97de1058cac7d5f44"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.5-beta/dive-cli_v0.0.5-beta_darwin_arm64.tar.gz"
      sha256 "a6b0da505f5f4086929f663fafd7b2e2746de100c3d2f5eb4e97b46b6c533f05"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.5-beta/dive-cli_v0.0.5-beta_linux_arm64.tar.gz"
      sha256 "d84d39a4f9b316d3924458ba9b6c15787a9e1eaf8e4c70b182d189b7fb65e98c"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.5-beta/dive-cli_v0.0.5-beta_linux_amd64.tar.gz"
      sha256 "6b0cb10410f267b37196c0d5ad815e2c749bac3e2b32444bf3ea258c59b27f5e"

      def install
        bin.install "dive"
      end
    end
  end
end
