# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv001Beta < Formula
  desc "CLI for managing Kurtosis environments."
  homepage "https://www.kurtosistech.com"
  version "0.0.1-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.1-beta/dive_darwin_arm64_v0.0.1-beta.tar.gz"
      sha256 "2870cd1917edbe12ddf6d827e482de2da96fdb0637f349fdc89a2a8c6cd7332d"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.1-beta/dive_darwin_x86_64_v0.0.1-beta.tar.gz"
      sha256 "3cb8f809822630ed7aa2b99cedd49a75348c1a134a487c1dcaa4deeaaf887429"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.1-beta/dive_linux_arm64_v0.0.1-beta.tar.gz"
      sha256 "e1f1c0c139a1fea0868a3036dbf6f4288c19ab733766bcebdce8eea31002d8b6"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.1-beta/dive_linux_x86_64_v0.0.1-beta.tar.gz"
      sha256 "881cf9464de0dde60cefce16001a298cfcfc3cd424e4b4bfa46d6f5a6df4214e"

      def install
        bin.install "dive"
      end
    end
  end
end
