# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCli < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.7-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.7-beta/dive-cli_v0.0.7-beta_darwin_arm64.tar.gz"
      sha256 "62ab232454f0c9cd8bca2fb83e78704f78327e88b4a4c2d7fc6e96bad1acc8b0"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.7-beta/dive-cli_v0.0.7-beta_darwin_amd64.tar.gz"
      sha256 "a6cd1f03e44ca8b0eeeaa92da6a28ad3ec7bcfe4a4fae237f3b82010489e17bf"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.7-beta/dive-cli_v0.0.7-beta_linux_arm64.tar.gz"
      sha256 "5ac96613d9de444f93441c86330223ca42a3705151b71cca53049f5a95a026f2"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.7-beta/dive-cli_v0.0.7-beta_linux_amd64.tar.gz"
      sha256 "734ab9f56596a5ee6cabb599c1877d4bfd1a5ad149de22242bd829fd642728b9"

      def install
        bin.install "dive"
      end
    end
  end
end
