# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv004Beta < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.4-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.4-beta/dive-cli_v0.0.4-beta_darwin_arm64.tar.gz"
      sha256 "4c591ca760130624a09c4c3b8dec5eb166adc6c70eb82c52d5f3a77f0ed85e23"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.4-beta/dive-cli_v0.0.4-beta_darwin_amd64.tar.gz"
      sha256 "e323149693e5cd8f010f039d8b928bf8d17877cdecf2d1fa290fbf7496154a16"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.4-beta/dive-cli_v0.0.4-beta_linux_amd64.tar.gz"
      sha256 "fa1135d69a85c5fe9427fc15adc406076200d36bc0f7e4c1b9869870f94a03b7"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.4-beta/dive-cli_v0.0.4-beta_linux_arm64.tar.gz"
      sha256 "45644d68cfb22711e45e81ea9a3c5b0efa86961bbe6ebb48d9df2d081fccb19b"

      def install
        bin.install "dive"
      end
    end
  end
end
