# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv0015Beta < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.15-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.15-beta/dive-cli_v0.0.15-beta_darwin_arm64.tar.gz"
      sha256 "760d5a833af5e592d5223dcfc0743056ba195188ea562a2f83e83cf6a14aa690"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.15-beta/dive-cli_v0.0.15-beta_darwin_amd64.tar.gz"
      sha256 "fe4d92aabd2c06bbf6689b4cef4621fc89a89f7e0209baffb052a7ced823c861"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.15-beta/dive-cli_v0.0.15-beta_linux_arm64.tar.gz"
      sha256 "d703a3ec4bf6e4f7531ea45ad031040bf03d57a71d174fa364c4e8600019e018"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.15-beta/dive-cli_v0.0.15-beta_linux_amd64.tar.gz"
      sha256 "64b684436383c25e75ea3982e5abc732099a8e5547f8fc7bc3c93d94e871482d"

      def install
        bin.install "dive"
      end
    end
  end
end
