# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCliATv0012Beta < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.0.12-beta"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.12-beta/dive-cli_v0.0.12-beta_darwin_amd64.tar.gz"
      sha256 "2a60339b1d2e92ce23de1e3e1739d7d6375fbdd92c9babdfbb959cbca9f13b99"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.12-beta/dive-cli_v0.0.12-beta_darwin_arm64.tar.gz"
      sha256 "7aeb52493491aaed5b29ba54bd52a0fe19a9228cf9585906818c06ca4d91b65c"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.12-beta/dive-cli_v0.0.12-beta_linux_amd64.tar.gz"
      sha256 "b6ba52767fbaec9ae82e61869c105d5f42d21edf04062a1b5a64df2195d12c80"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.0.12-beta/dive-cli_v0.0.12-beta_linux_arm64.tar.gz"
      sha256 "b27d24bc25d6f736fe2aa17acc82f45f39ab32d82c9bb0985d9e39782c7c1226"

      def install
        bin.install "dive"
      end
    end
  end
end
