# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiveCli < Formula
  desc "CLI for Dive Package"
  homepage "https://hugobyte.com"
  version "0.1.0"
  license "Apache 2.0"

  depends_on "kurtosis-cli@0.86.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.0/dive-cli_v0.1.0_darwin_amd64.tar.gz"
      sha256 "c120f7daa19cea96457d230c6ff565a9cf699d362225b69f8082fbcf9b754415"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.0/dive-cli_v0.1.0_darwin_arm64.tar.gz"
      sha256 "997b1e6fb8288d0be2f08f79c3d2e7762fa67375e1b2f73ea5f8d36b1871d8d5"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.0/dive-cli_v0.1.0_linux_arm64.tar.gz"
      sha256 "a9074929dc973533530b0d7743ef00c2ebc6ff6c06c1d60a38b170afcd8ca3a4"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HugoByte/DIVE/releases/download/v0.1.0/dive-cli_v0.1.0_linux_amd64.tar.gz"
      sha256 "58c8dd9423b6ec70bfafe19215a3197d8b8d0b0da0a6024e27ea4eb41caa7ca4"

      def install
        bin.install "dive"
      end
    end
  end
end
